#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v4
# autospec commit: 1ab68ca
#
Name     : libsecret
Version  : 0.21.4
Release  : 33
URL      : https://download.gnome.org/sources/libsecret/0.21/libsecret-0.21.4.tar.xz
Source0  : https://download.gnome.org/sources/libsecret/0.21/libsecret-0.21.4.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 LGPL-2.1
Requires: libsecret-bin = %{version}-%{release}
Requires: libsecret-data = %{version}-%{release}
Requires: libsecret-lib = %{version}-%{release}
Requires: libsecret-license = %{version}-%{release}
Requires: libsecret-locales = %{version}-%{release}
Requires: libsecret-man = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : dbus-dev
BuildRequires : dbus-python
BuildRequires : docbook-xml
BuildRequires : gjs
BuildRequires : gobject-introspection-dev
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(tss2-esys)
BuildRequires : pkgconfig(tss2-mu)
BuildRequires : pkgconfig(tss2-rc)
BuildRequires : pkgconfig(tss2-tctildr)
BuildRequires : pygobject
BuildRequires : python3
BuildRequires : vala-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libsecret
=========
A [GObject]-based library for accessing the Secret Service API of the
[freedesktop.org project], a cross-desktop effort to access passwords, tokens
and other types of secrets. libsecret provides a convenient wrapper for these
methods so consumers do not have to call the low-level DBus methods.

%package bin
Summary: bin components for the libsecret package.
Group: Binaries
Requires: libsecret-data = %{version}-%{release}
Requires: libsecret-license = %{version}-%{release}

%description bin
bin components for the libsecret package.


%package data
Summary: data components for the libsecret package.
Group: Data

%description data
data components for the libsecret package.


%package dev
Summary: dev components for the libsecret package.
Group: Development
Requires: libsecret-lib = %{version}-%{release}
Requires: libsecret-bin = %{version}-%{release}
Requires: libsecret-data = %{version}-%{release}
Provides: libsecret-devel = %{version}-%{release}
Requires: libsecret = %{version}-%{release}

%description dev
dev components for the libsecret package.


%package lib
Summary: lib components for the libsecret package.
Group: Libraries
Requires: libsecret-data = %{version}-%{release}
Requires: libsecret-license = %{version}-%{release}

%description lib
lib components for the libsecret package.


%package license
Summary: license components for the libsecret package.
Group: Default

%description license
license components for the libsecret package.


%package locales
Summary: locales components for the libsecret package.
Group: Default

%description locales
locales components for the libsecret package.


%package man
Summary: man components for the libsecret package.
Group: Default

%description man
man components for the libsecret package.


%prep
%setup -q -n libsecret-0.21.4
cd %{_builddir}/libsecret-0.21.4
pushd ..
cp -a libsecret-0.21.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709739907
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dgtk_doc=false  builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dgtk_doc=false  builddiravx2
ninja -v -C builddiravx2

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
dbus-run-session meson test -C builddir || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/libsecret
cp %{_builddir}/libsecret-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libsecret/7c7d178d9ce31b21a4869940a881b043b086f007 || :
cp %{_builddir}/libsecret-%{version}/COPYING.TESTS %{buildroot}/usr/share/package-licenses/libsecret/22e01c37d5bbe7f728acd042bb9d6972081bfb48 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang libsecret
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/secret-tool
/usr/bin/secret-tool

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Secret-1.typelib
/usr/share/gir-1.0/*.gir
/usr/share/vala/vapi/libsecret-1.deps
/usr/share/vala/vapi/libsecret-1.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/libsecret-1/libsecret/secret-attributes.h
/usr/include/libsecret-1/libsecret/secret-backend.h
/usr/include/libsecret-1/libsecret/secret-collection.h
/usr/include/libsecret-1/libsecret/secret-enum-types.h
/usr/include/libsecret-1/libsecret/secret-item.h
/usr/include/libsecret-1/libsecret/secret-password.h
/usr/include/libsecret-1/libsecret/secret-paths.h
/usr/include/libsecret-1/libsecret/secret-prompt.h
/usr/include/libsecret-1/libsecret/secret-retrievable.h
/usr/include/libsecret-1/libsecret/secret-schema.h
/usr/include/libsecret-1/libsecret/secret-schemas.h
/usr/include/libsecret-1/libsecret/secret-service.h
/usr/include/libsecret-1/libsecret/secret-types.h
/usr/include/libsecret-1/libsecret/secret-value.h
/usr/include/libsecret-1/libsecret/secret-version.h
/usr/include/libsecret-1/libsecret/secret.h
/usr/lib64/libsecret-1.so
/usr/lib64/pkgconfig/libsecret-1.pc
/usr/lib64/pkgconfig/libsecret-unstable.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libsecret-1.so.0.0.0
/usr/lib64/libsecret-1.so.0
/usr/lib64/libsecret-1.so.0.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libsecret/22e01c37d5bbe7f728acd042bb9d6972081bfb48
/usr/share/package-licenses/libsecret/7c7d178d9ce31b21a4869940a881b043b086f007

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/secret-tool.1

%files locales -f libsecret.lang
%defattr(-,root,root,-)

