#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libsecret
Version  : 0.18.6
Release  : 10
URL      : https://download.gnome.org/sources/libsecret/0.18/libsecret-0.18.6.tar.xz
Source0  : https://download.gnome.org/sources/libsecret/0.18/libsecret-0.18.6.tar.xz
Summary  : GObject bindings for Secret Service API
Group    : Development/Tools
License  : Apache-2.0 LGPL-2.1
Requires: libsecret-bin
Requires: libsecret-data
Requires: libsecret-lib
Requires: libsecret-doc
Requires: libsecret-locales
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : intltool
BuildRequires : libgcrypt-dev
BuildRequires : libgpg-error-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : python3

%description
GObject based library for accessing the Secret Service API.

%package bin
Summary: bin components for the libsecret package.
Group: Binaries
Requires: libsecret-data

%description bin
bin components for the libsecret package.


%package data
Summary: data components for the libsecret package.
Group: Data

%description data
data components for the libsecret package.


%package dev
Summary: dev components for the libsecret package.
Group: Development
Requires: libsecret-lib
Requires: libsecret-bin
Requires: libsecret-data
Provides: libsecret-devel

%description dev
dev components for the libsecret package.


%package doc
Summary: doc components for the libsecret package.
Group: Documentation

%description doc
doc components for the libsecret package.


%package lib
Summary: lib components for the libsecret package.
Group: Libraries
Requires: libsecret-data

%description lib
lib components for the libsecret package.


%package locales
Summary: locales components for the libsecret package.
Group: Default

%description locales
locales components for the libsecret package.


%prep
%setup -q -n libsecret-0.18.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1522340897
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1522340897
rm -rf %{buildroot}
%make_install
%find_lang libsecret

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/secret-tool

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Secret-1.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/libsecret-1/libsecret/secret-attributes.h
/usr/include/libsecret-1/libsecret/secret-collection.h
/usr/include/libsecret-1/libsecret/secret-enum-types.h
/usr/include/libsecret-1/libsecret/secret-item.h
/usr/include/libsecret-1/libsecret/secret-password.h
/usr/include/libsecret-1/libsecret/secret-paths.h
/usr/include/libsecret-1/libsecret/secret-prompt.h
/usr/include/libsecret-1/libsecret/secret-schema.h
/usr/include/libsecret-1/libsecret/secret-schemas.h
/usr/include/libsecret-1/libsecret/secret-service.h
/usr/include/libsecret-1/libsecret/secret-types.h
/usr/include/libsecret-1/libsecret/secret-value.h
/usr/include/libsecret-1/libsecret/secret.h
/usr/lib64/libsecret-1.so
/usr/lib64/pkgconfig/libsecret-1.pc
/usr/lib64/pkgconfig/libsecret-unstable.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
/usr/share/gtk-doc/html/libsecret-1/SecretCollection.html
/usr/share/gtk-doc/html/libsecret-1/SecretItem.html
/usr/share/gtk-doc/html/libsecret-1/SecretPrompt.html
/usr/share/gtk-doc/html/libsecret-1/SecretService.html
/usr/share/gtk-doc/html/libsecret-1/SecretValue.html
/usr/share/gtk-doc/html/libsecret-1/annotation-glossary.html
/usr/share/gtk-doc/html/libsecret-1/c-examples.html
/usr/share/gtk-doc/html/libsecret-1/c-lookup-example.html
/usr/share/gtk-doc/html/libsecret-1/c-remove-example.html
/usr/share/gtk-doc/html/libsecret-1/c-store-example.html
/usr/share/gtk-doc/html/libsecret-1/complete.html
/usr/share/gtk-doc/html/libsecret-1/examples.html
/usr/share/gtk-doc/html/libsecret-1/home.png
/usr/share/gtk-doc/html/libsecret-1/index.html
/usr/share/gtk-doc/html/libsecret-1/js-examples.html
/usr/share/gtk-doc/html/libsecret-1/js-lookup-example.html
/usr/share/gtk-doc/html/libsecret-1/js-remove-example.html
/usr/share/gtk-doc/html/libsecret-1/js-store-example.html
/usr/share/gtk-doc/html/libsecret-1/left-insensitive.png
/usr/share/gtk-doc/html/libsecret-1/left.png
/usr/share/gtk-doc/html/libsecret-1/libsecret-1.devhelp2
/usr/share/gtk-doc/html/libsecret-1/libsecret-DBus-Path-Related-Functions.html
/usr/share/gtk-doc/html/libsecret-1/libsecret-Password-storage.html
/usr/share/gtk-doc/html/libsecret-1/libsecret-Secret-Attributes.html
/usr/share/gtk-doc/html/libsecret-1/libsecret-SecretError.html
/usr/share/gtk-doc/html/libsecret-1/libsecret-SecretSchema.html
/usr/share/gtk-doc/html/libsecret-1/migrating-api.html
/usr/share/gtk-doc/html/libsecret-1/migrating-introduction.html
/usr/share/gtk-doc/html/libsecret-1/migrating-items.html
/usr/share/gtk-doc/html/libsecret-1/migrating-keyrings.html
/usr/share/gtk-doc/html/libsecret-1/migrating-locking.html
/usr/share/gtk-doc/html/libsecret-1/migrating-memory.html
/usr/share/gtk-doc/html/libsecret-1/migrating-misc.html
/usr/share/gtk-doc/html/libsecret-1/migrating-removing.html
/usr/share/gtk-doc/html/libsecret-1/migrating-schemas.html
/usr/share/gtk-doc/html/libsecret-1/migrating-searching.html
/usr/share/gtk-doc/html/libsecret-1/migrating-storing.html
/usr/share/gtk-doc/html/libsecret-1/migrating.html
/usr/share/gtk-doc/html/libsecret-1/py-examples.html
/usr/share/gtk-doc/html/libsecret-1/py-lookup-example.html
/usr/share/gtk-doc/html/libsecret-1/py-remove-example.html
/usr/share/gtk-doc/html/libsecret-1/py-store-example.html
/usr/share/gtk-doc/html/libsecret-1/right-insensitive.png
/usr/share/gtk-doc/html/libsecret-1/right.png
/usr/share/gtk-doc/html/libsecret-1/simple.html
/usr/share/gtk-doc/html/libsecret-1/style.css
/usr/share/gtk-doc/html/libsecret-1/up-insensitive.png
/usr/share/gtk-doc/html/libsecret-1/up.png
/usr/share/gtk-doc/html/libsecret-1/using-c.html
/usr/share/gtk-doc/html/libsecret-1/using-js.html
/usr/share/gtk-doc/html/libsecret-1/using-python.html
/usr/share/gtk-doc/html/libsecret-1/using-vala.html
/usr/share/gtk-doc/html/libsecret-1/using.html
/usr/share/gtk-doc/html/libsecret-1/vala-examples.html
/usr/share/gtk-doc/html/libsecret-1/vala-lookup-example.html
/usr/share/gtk-doc/html/libsecret-1/vala-remove-example.html
/usr/share/gtk-doc/html/libsecret-1/vala-store-example.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsecret-1.so.0
/usr/lib64/libsecret-1.so.0.0.0

%files locales -f libsecret.lang
%defattr(-,root,root,-)

